/*
 * Node.js-compatible CLI for QuickJS-NG
 *
 * This is NOT Node.js. It is a QuickJS-based runtime with a Node.js
 * compatibility layer that provides require(), process, Buffer, and
 * core Node.js modules (fs, path, events, os, util, stream, etc.).
 *
 * Based on qjs.c from QuickJS-NG.
 */
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <time.h>
#include <sys/stat.h>

#include "cutils.h"
#include "quickjs.h"
#include "quickjs-libc.h"

#include "node-compat-native/node-native.h"
#include "node-compat-native/socket.h"
#include "node-compat-native/tls.h"

/* Generated bytecode from node-compat/bootstrap.js */
extern const uint8_t qjsc_bootstrap[];
extern const uint32_t qjsc_bootstrap_size;

/* QuickJS built-in bytecodes */
extern const uint8_t qjsc_repl[];
extern const uint32_t qjsc_repl_size;

static int node__argc;
static char **node__argv;

/* Node-flavoured event loop. Wraps js_std_loop_once() so we can drive the
   socket fd-watch table on every iteration. Exit when no JS jobs, no
   timers, and no pending socket watches remain. */
static int js_node_loop(JSContext *ctx)
{
    JSRuntime *rt = JS_GetRuntime(ctx);

    for (;;) {
        int delay = js_std_loop_once(ctx); /* drains microtasks + 1 timer */
        if (delay == -2) return -1;        /* JS error */

        int dispatched = js_node_socket_dispatch(ctx);
        dispatched += js_node_tls_dispatch(ctx);
        int has_watches = js_node_socket_has_watches() ||
                          js_node_tls_has_watches();
        int jobs_pending = JS_IsJobPending(rt);

        if (!has_watches && !jobs_pending && delay == -1) {
            return JS_HasException(ctx) ? -1 : 0;
        }

        if (jobs_pending || delay == 0 || dispatched > 0) continue;

        int sleep_ms;
        if (has_watches) {
            sleep_ms = (delay > 0 && delay < 5) ? delay : 5;
        } else {
            sleep_ms = delay;
        }
        if (sleep_ms <= 0) continue;
        struct timespec ts = {
            .tv_sec  = sleep_ms / 1000,
            .tv_nsec = (sleep_ms % 1000) * 1000000L,
        };
        nanosleep(&ts, NULL);
    }
}

static JSValue js_gc(JSContext *ctx, JSValueConst this_val,
                     int argc, JSValueConst *argv)
{
    JS_RunGC(JS_GetRuntime(ctx));
    return JS_UNDEFINED;
}

static const JSCFunctionListEntry global_obj[] = {
    JS_CFUNC_DEF("gc", 0, js_gc),
};

static JSContext *JS_NewNodeContext(JSRuntime *rt)
{
    JSContext *ctx;
    ctx = JS_NewContext(rt);
    if (!ctx)
        return NULL;

    /* Register QuickJS system modules (used by bootstrap) */
    js_init_module_std(ctx, "qjs:std");
    js_init_module_os(ctx, "qjs:os");
    js_init_module_bjson(ctx, "qjs:bjson");
    js_init_module_node_native(ctx, "qjs:node");

    JSValue global = JS_GetGlobalObject(ctx);
    JS_SetPropertyFunctionList(ctx, global, global_obj, countof(global_obj));

    /* Set up execArgv and argv0 for the bootstrap to pick up */
    JSValue args = JS_NewArray(ctx);
    for (int i = 0; i < node__argc; i++) {
        JS_SetPropertyUint32(ctx, args, i, JS_NewString(ctx, node__argv[i]));
    }
    JS_SetPropertyStr(ctx, global, "execArgv", args);
    JS_SetPropertyStr(ctx, global, "argv0",
                      JS_NewString(ctx, node__argv[0]));

    JS_FreeValue(ctx, global);
    return ctx;
}

static int eval_buf(JSContext *ctx, const void *buf, int buf_len,
                    const char *filename, int eval_flags)
{
    JSValue val;
    int ret;

    if ((eval_flags & JS_EVAL_TYPE_MASK) == JS_EVAL_TYPE_MODULE) {
        val = JS_Eval(ctx, buf, buf_len, filename,
                      eval_flags | JS_EVAL_FLAG_COMPILE_ONLY);
        if (!JS_IsException(val)) {
            js_module_set_import_meta(ctx, val, false, true);
            val = JS_EvalFunction(ctx, val);
        }
        val = js_std_await(ctx, val);
    } else {
        val = JS_Eval(ctx, buf, buf_len, filename, eval_flags);
    }
    if (JS_IsException(val)) {
        js_std_dump_error(ctx);
        ret = -1;
    } else {
        ret = 0;
    }
    JS_FreeValue(ctx, val);
    return ret;
}

static int eval_file(JSContext *ctx, const char *filename, int module)
{
    uint8_t *buf;
    int ret, eval_flags;
    size_t buf_len;

    buf = js_load_file(ctx, &buf_len, filename);
    if (!buf) {
        fprintf(stderr, "node: cannot load '%s': %s\n", filename, strerror(errno));
        return -1;
    }

    if (module < 0) {
        /* Auto-detect: .mjs = module, .cjs = script, else check content */
        module = (js__has_suffix(filename, ".mjs") ||
                  (!js__has_suffix(filename, ".cjs") &&
                   JS_DetectModule((const char *)buf, buf_len)));
    }

    if (module)
        eval_flags = JS_EVAL_TYPE_MODULE;
    else
        eval_flags = JS_EVAL_TYPE_GLOBAL;

    ret = eval_buf(ctx, buf, buf_len, filename, eval_flags);
    js_free(ctx, buf);
    return ret;
}

/* ============================================================
 * Node-style module resolver for ESM dynamic import().
 *
 * QuickJS's default loader treats every specifier as a literal filename.
 * Node-compat callers (chiefly the bootstrap's require() chain awaiting
 * `import('chalk')`) need bare specifiers, package-relative `#imports`,
 * and `node:` builtins to resolve like Node does. This block adds:
 *
 *   - node_module_normalize: bare → node_modules walk + package.json
 *     (`exports`/`main`); `#name` → package.json#imports of the importer's
 *     package; relative/absolute → default behaviour, plus directory →
 *     package.json#main.
 *   - node_module_loader: synthesises an ESM bridge for `node:foo` that
 *     re-exports `globalThis.require('foo')` as default, and otherwise
 *     delegates to QuickJS's stock file-based loader.
 * ============================================================ */

static int nm_is_regular_file(const char *path)
{
    struct stat st;
    return stat(path, &st) == 0 && S_ISREG(st.st_mode);
}

static int nm_is_directory(const char *path)
{
    struct stat st;
    return stat(path, &st) == 0 && S_ISDIR(st.st_mode);
}

/* Allocate `dirname(p)` in ctx's heap. The caller frees with js_free. */
static char *nm_dirname(JSContext *ctx, const char *p)
{
    const char *slash = strrchr(p, '/');
    if (!slash) return js_strdup(ctx, ".");
    if (slash == p) return js_strdup(ctx, "/");
    size_t len = slash - p;
    char *out = js_malloc(ctx, len + 1);
    if (!out) return NULL;
    memcpy(out, p, len);
    out[len] = '\0';
    return out;
}

static char *nm_join(JSContext *ctx, const char *a, const char *b)
{
    size_t la = strlen(a), lb = strlen(b);
    int need_slash = (la > 0 && a[la - 1] != '/' && b[0] != '/');
    char *out = js_malloc(ctx, la + lb + (need_slash ? 1 : 0) + 1);
    if (!out) return NULL;
    memcpy(out, a, la);
    size_t off = la;
    if (need_slash) out[off++] = '/';
    memcpy(out + off, b, lb);
    out[off + lb] = '\0';
    return out;
}

/* Read whole file; returns malloc'd null-terminated string (caller frees with
   js_free), or NULL on error. */
static char *nm_read_file(JSContext *ctx, const char *path, size_t *out_len)
{
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return NULL; }
    long sz = ftell(f);
    if (sz < 0) { fclose(f); return NULL; }
    if (fseek(f, 0, SEEK_SET) != 0) { fclose(f); return NULL; }
    char *buf = js_malloc(ctx, (size_t)sz + 1);
    if (!buf) { fclose(f); return NULL; }
    size_t n = fread(buf, 1, (size_t)sz, f);
    fclose(f);
    buf[n] = '\0';
    if (out_len) *out_len = n;
    return buf;
}

static JSValue nm_load_package_json(JSContext *ctx, const char *pkg_dir)
{
    char *pjson = nm_join(ctx, pkg_dir, "package.json");
    if (!pjson) return JS_EXCEPTION;
    if (!nm_is_regular_file(pjson)) { js_free(ctx, pjson); return JS_UNDEFINED; }
    size_t buf_len;
    char *buf = nm_read_file(ctx, pjson, &buf_len);
    JSValue parsed = JS_UNDEFINED;
    if (buf) parsed = JS_ParseJSON(ctx, buf, buf_len, pjson);
    js_free(ctx, buf);
    js_free(ctx, pjson);
    if (JS_IsException(parsed)) {
        /* Tolerate malformed package.json — treat as missing. */
        JS_FreeValue(ctx, JS_GetException(ctx));
        return JS_UNDEFINED;
    }
    return parsed;
}

/* Walk up from `start_dir` to find the nearest enclosing package.json.
   Returns malloc'd directory path on success, NULL otherwise. */
static char *nm_find_package_root(JSContext *ctx, const char *start_dir)
{
    char *dir = js_strdup(ctx, start_dir);
    if (!dir) return NULL;
    while (dir[0]) {
        char *pjson = nm_join(ctx, dir, "package.json");
        if (!pjson) { js_free(ctx, dir); return NULL; }
        int ok = nm_is_regular_file(pjson);
        js_free(ctx, pjson);
        if (ok) return dir;
        if (!strcmp(dir, "/")) break;
        char *parent = nm_dirname(ctx, dir);
        if (!parent) { js_free(ctx, dir); return NULL; }
        /* dirname(".") == "." — guard against the fixed point before freeing. */
        int stuck = !strcmp(parent, dir);
        js_free(ctx, dir);
        if (stuck) { js_free(ctx, parent); return NULL; }
        dir = parent;
    }
    js_free(ctx, dir);
    return NULL;
}

/* Pick a value out of a conditional-export object.
   ESM priority is `node` → `import` → `default`. CJS callers don't reach this
   path (they use the JS-side resolver). Returns a JSValue that the caller
   must JS_FreeValue. JS_UNDEFINED if no condition matched. */
static JSValue nm_pick_condition(JSContext *ctx, JSValueConst obj)
{
    static const char *conds[] = { "node", "import", "default" };
    for (size_t i = 0; i < countof(conds); i++) {
        JSValue v = JS_GetPropertyStr(ctx, obj, conds[i]);
        if (JS_IsException(v)) return JS_EXCEPTION;
        if (!JS_IsUndefined(v)) return v;
        JS_FreeValue(ctx, v);
    }
    return JS_UNDEFINED;
}

/* Walk a (possibly nested) conditional/string node from package.json
   `exports` or `imports`. Strings ("./foo.js") are returned as-is; objects
   are recursively resolved via nm_pick_condition. Returns NULL on no match. */
static char *nm_collapse_target(JSContext *ctx, JSValueConst node)
{
    JSValue cur = JS_DupValue(ctx, node);
    while (JS_IsObject(cur) && !JS_IsArray(cur)) {
        JSValue picked = nm_pick_condition(ctx, cur);
        JS_FreeValue(ctx, cur);
        if (JS_IsException(picked)) return NULL;
        if (JS_IsUndefined(picked)) return NULL;
        cur = picked;
    }
    if (!JS_IsString(cur)) { JS_FreeValue(ctx, cur); return NULL; }
    const char *s = JS_ToCString(ctx, cur);
    char *out = s ? js_strdup(ctx, s) : NULL;
    JS_FreeCString(ctx, s);
    JS_FreeValue(ctx, cur);
    return out;
}

/* Resolve `pkg_dir` + a target string ("./source/index.js") to an absolute
   path. Validates the file exists; otherwise returns NULL. */
static char *nm_resolve_relative_target(JSContext *ctx,
                                         const char *pkg_dir,
                                         const char *target)
{
    if (target[0] == '.' && target[1] == '/') target += 2;
    char *full = nm_join(ctx, pkg_dir, target);
    if (!full) return NULL;
    if (nm_is_regular_file(full)) return full;
    js_free(ctx, full);
    return NULL;
}

/* Resolve a bare specifier inside `pkg_dir`'s package.json `exports` /
   `main`. `subpath` is "" (root) or "./util" etc. */
static char *nm_resolve_in_package(JSContext *ctx,
                                    const char *pkg_dir,
                                    const char *subpath)
{
    JSValue pkg = nm_load_package_json(ctx, pkg_dir);
    if (JS_IsException(pkg)) return NULL;
    if (JS_IsUndefined(pkg)) {
        /* No package.json — fall back to <pkg_dir>/index.js */
        char *idx = nm_join(ctx, pkg_dir, "index.js");
        if (idx && nm_is_regular_file(idx)) return idx;
        js_free(ctx, idx);
        return NULL;
    }

    char *result = NULL;
    JSValue exports_v = JS_GetPropertyStr(ctx, pkg, "exports");
    if (!JS_IsUndefined(exports_v) && !JS_IsException(exports_v)) {
        JSValue target_node = JS_UNDEFINED;
        if (JS_IsString(exports_v)) {
            if (!subpath[0])
                target_node = JS_DupValue(ctx, exports_v);
        } else if (JS_IsObject(exports_v)) {
            const char *key = subpath[0] ? subpath : ".";
            JSValue v = JS_GetPropertyStr(ctx, exports_v, key);
            if (!JS_IsUndefined(v) && !JS_IsException(v)) {
                target_node = v;
            } else {
                JS_FreeValue(ctx, v);
                /* No subpath keys at all → conditional exports for root. */
                if (!subpath[0]) target_node = JS_DupValue(ctx, exports_v);
            }
        }
        if (!JS_IsUndefined(target_node)) {
            char *target = nm_collapse_target(ctx, target_node);
            JS_FreeValue(ctx, target_node);
            if (target) {
                result = nm_resolve_relative_target(ctx, pkg_dir, target);
                js_free(ctx, target);
            }
        }
    }
    JS_FreeValue(ctx, exports_v);

    /* Fall back to `main` (or index.js) if `exports` didn't resolve. Only
       valid for the root subpath — npm doesn't request subpaths against
       legacy main-only packages. */
    if (!result && !subpath[0]) {
        JSValue main_v = JS_GetPropertyStr(ctx, pkg, "main");
        const char *main_s = JS_IsString(main_v) ? JS_ToCString(ctx, main_v) : NULL;
        const char *target = main_s ? main_s : "index.js";
        char *full = nm_join(ctx, pkg_dir, target);
        if (full) {
            if (nm_is_regular_file(full)) {
                result = full;
            } else {
                /* main may be extension-less or directory — try .js then index.js
                   in a single reusable buffer. */
                size_t fl = strlen(full);
                char *cand = js_malloc(ctx, fl + 10);
                if (cand) {
                    snprintf(cand, fl + 10, "%s.js", full);
                    if (nm_is_regular_file(cand)) {
                        result = cand;
                    } else {
                        snprintf(cand, fl + 10, "%s/index.js", full);
                        if (nm_is_regular_file(cand)) {
                            result = cand;
                        } else {
                            js_free(ctx, cand);
                        }
                    }
                }
                js_free(ctx, full);
            }
        }
        JS_FreeCString(ctx, main_s);
        JS_FreeValue(ctx, main_v);
    }

    JS_FreeValue(ctx, pkg);
    return result;
}

/* Bare specifier (`chalk`, `chalk/foo`): walk from base's directory upward
   looking for `node_modules/<head>`. */
static char *nm_resolve_bare(JSContext *ctx, const char *base, const char *spec)
{
    /* Split spec into `head` (chalk, @scope/name) and `subpath` (./foo or ""). */
    const char *slash;
    size_t head_len;
    if (spec[0] == '@') {
        slash = strchr(spec + 1, '/');
        if (slash) {
            const char *slash2 = strchr(slash + 1, '/');
            head_len = slash2 ? (size_t)(slash2 - spec) : strlen(spec);
        } else {
            head_len = strlen(spec);
        }
    } else {
        slash = strchr(spec, '/');
        head_len = slash ? (size_t)(slash - spec) : strlen(spec);
    }

    char head[256];
    if (head_len >= sizeof(head)) return NULL;
    memcpy(head, spec, head_len);
    head[head_len] = '\0';

    char subpath[1024];
    if (head_len == strlen(spec)) {
        subpath[0] = '\0';
    } else {
        if (snprintf(subpath, sizeof(subpath), ".%s", spec + head_len) < 0)
            return NULL;
    }

    char *dir = nm_dirname(ctx, base && base[0] ? base : "/");
    if (!dir) return NULL;
    char *result = NULL;
    while (1) {
        char *nm_dir = js_malloc(ctx,
            strlen(dir) + strlen("/node_modules/") + head_len + 1);
        if (!nm_dir) break;
        sprintf(nm_dir, "%s/node_modules/%s", dir, head);
        if (nm_is_directory(nm_dir)) {
            result = nm_resolve_in_package(ctx, nm_dir, subpath);
            js_free(ctx, nm_dir);
            if (result) break;
        } else {
            js_free(ctx, nm_dir);
        }
        if (!strcmp(dir, "/")) break;
        char *parent = nm_dirname(ctx, dir);
        if (!parent) { js_free(ctx, dir); return NULL; }
        int stuck = !strcmp(parent, dir);
        js_free(ctx, dir);
        if (stuck) { js_free(ctx, parent); dir = NULL; break; }
        dir = parent;
    }
    js_free(ctx, dir);
    return result;
}

/* `#name` subpath import: resolve via the importer's package.json `imports`. */
static char *nm_resolve_subpath_import(JSContext *ctx, const char *base,
                                        const char *spec)
{
    char *base_dir = nm_dirname(ctx, base && base[0] ? base : "/");
    if (!base_dir) return NULL;
    char *pkg_root = nm_find_package_root(ctx, base_dir);
    js_free(ctx, base_dir);
    if (!pkg_root) return NULL;

    JSValue pkg = nm_load_package_json(ctx, pkg_root);
    char *result = NULL;
    if (JS_IsObject(pkg)) {
        JSValue imports = JS_GetPropertyStr(ctx, pkg, "imports");
        if (JS_IsObject(imports)) {
            JSValue node = JS_GetPropertyStr(ctx, imports, spec);
            if (!JS_IsUndefined(node) && !JS_IsException(node)) {
                char *target = nm_collapse_target(ctx, node);
                if (target) {
                    result = nm_resolve_relative_target(ctx, pkg_root, target);
                    js_free(ctx, target);
                }
            }
            JS_FreeValue(ctx, node);
        }
        JS_FreeValue(ctx, imports);
    }
    JS_FreeValue(ctx, pkg);
    js_free(ctx, pkg_root);
    return result;
}

/* Same shape as js_default_module_normalize_name in quickjs.c — trims
   leading `./` and `../` segments, joins onto base's dirname. We re-do
   this in C rather than calling out because we also need to collapse
   the result against package.json#main when it lands on a directory. */
static char *nm_normalize_relative(JSContext *ctx, const char *base, const char *name)
{
    const char *r = name;
    char *filename;
    int cap, len;
    const char *base_end = base ? strrchr(base, '/') : NULL;
    len = base_end ? (int)(base_end - base) : 0;
    cap = len + (int)strlen(name) + 2;
    filename = js_malloc(ctx, cap);
    if (!filename) return NULL;
    if (len > 0) memcpy(filename, base, len);
    filename[len] = '\0';

    while (1) {
        if (r[0] == '.' && r[1] == '/') {
            r += 2;
        } else if (r[0] == '.' && r[1] == '.' && r[2] == '/') {
            char *p;
            if (filename[0] == '\0') break;
            p = strrchr(filename, '/');
            if (!p) p = filename; else p++;
            if (!strcmp(p, ".") || !strcmp(p, "..")) break;
            if (p > filename) p--;
            *p = '\0';
            r += 3;
        } else {
            break;
        }
    }
    if (filename[0] != '\0') js__pstrcat(filename, cap, "/");
    js__pstrcat(filename, cap, r);
    return filename;
}

/* Promote a directory path to its package.json#main (or index.js). Used
   when the JS side hands us an absolute path that points at a directory
   instead of a file. */
static char *nm_collapse_directory(JSContext *ctx, char *path)
{
    if (!nm_is_directory(path)) return path;
    char *resolved = nm_resolve_in_package(ctx, path, "");
    if (resolved) { js_free(ctx, path); return resolved; }
    return path;
}

static char *node_module_normalize(JSContext *ctx, const char *base_name,
                                    const char *name, void *opaque)
{
    if (!strncmp(name, "qjs:", 4) || !strncmp(name, "node:", 5))
        return js_strdup(ctx, name);

    if (name[0] == '/')
        return nm_collapse_directory(ctx, js_strdup(ctx, name));

    if (name[0] == '.') {
        char *out = nm_normalize_relative(ctx, base_name ? base_name : "", name);
        return out ? nm_collapse_directory(ctx, out) : NULL;
    }

    if (name[0] == '#') {
        char *out = nm_resolve_subpath_import(ctx, base_name, name);
        if (out) return out;
        JS_ThrowReferenceError(ctx,
            "could not resolve subpath import '%s' from '%s'",
            name, base_name ? base_name : "<anonymous>");
        return NULL;
    }

    /* bare specifier */
    char *out = nm_resolve_bare(ctx, base_name, name);
    if (out) return out;
    JS_ThrowReferenceError(ctx,
        "could not resolve module '%s' from '%s'",
        name, base_name ? base_name : "<anonymous>");
    return NULL;
}

static JSModuleDef *node_module_loader(JSContext *ctx, const char *module_name,
                                        void *opaque, JSValueConst attributes)
{
    if (!strncmp(module_name, "node:", 5)) {
        char src[256];
        int n = snprintf(src, sizeof(src),
            "const _m = globalThis.require(\"%s\");\nexport default _m;\n",
            module_name + 5);
        if (n < 0 || n >= (int)sizeof(src)) {
            JS_ThrowInternalError(ctx, "node: builtin name too long: %s",
                                  module_name);
            return NULL;
        }
        JSValue func = JS_Eval(ctx, src, strlen(src), module_name,
                               JS_EVAL_TYPE_MODULE | JS_EVAL_FLAG_COMPILE_ONLY);
        if (JS_IsException(func)) return NULL;
        if (js_module_set_import_meta(ctx, func, false, false) < 0) {
            JS_FreeValue(ctx, func);
            return NULL;
        }
        JSModuleDef *m = JS_VALUE_GET_PTR(func);
        JS_FreeValue(ctx, func);
        return m;
    }
    return js_module_loader(ctx, module_name, opaque, attributes);
}

static void help(void)
{
    printf("node (QuickJS-NG v%s Node.js compatibility layer)\n"
           "This is NOT Node.js. It provides Node.js API compatibility\n"
           "via QuickJS-NG with POSIX os/std modules.\n"
           "\n"
           "usage: node [options] [script.js] [args...]\n"
           "       node -e 'code'       evaluate code\n"
           "       node -p 'expr'       evaluate and print\n"
           "       node --version       print version\n"
           "       node -h, --help      show help\n"
           "\n"
           "Supported Node.js modules:\n"
           "  assert, buffer, child_process, cluster, crypto, dns,\n"
           "  events, fs, http, https, module, net, os, path,\n"
           "  perf_hooks, punycode, querystring, readline, stream,\n"
           "  string_decoder, timers, tty, url, util, v8, vm,\n"
           "  worker_threads, zlib\n",
           JS_GetVersion());
    exit(0);
}

int main(int argc, char **argv)
{
    JSRuntime *rt;
    JSContext *ctx;
    int r = 0;
    int optind = 1;
    char *expr = NULL;
    int print_result = 0;
    int interactive = 0;
    int module = -1;

    node__argc = argc;
    node__argv = argv;

    /* Parse options */
    while (optind < argc && argv[optind][0] == '-') {
        const char *arg = argv[optind];

        if (!strcmp(arg, "-h") || !strcmp(arg, "--help")) {
            help();
        } else if (!strcmp(arg, "-v") || !strcmp(arg, "--version")) {
            printf("v22.0.0\n");
            return 0;
        } else if (!strcmp(arg, "-e") || !strcmp(arg, "--eval")) {
            optind++;
            if (optind >= argc) {
                fprintf(stderr, "node: missing argument for -e\n");
                return 1;
            }
            expr = argv[optind++];
            break;
        } else if (!strcmp(arg, "-p") || !strcmp(arg, "--print")) {
            optind++;
            if (optind >= argc) {
                fprintf(stderr, "node: missing argument for -p\n");
                return 1;
            }
            expr = argv[optind++];
            print_result = 1;
            break;
        } else if (!strcmp(arg, "-i") || !strcmp(arg, "--interactive")) {
            interactive = 1;
            optind++;
        } else if (!strcmp(arg, "--input-type=module")) {
            module = 1;
            optind++;
        } else if (!strcmp(arg, "-r") || !strcmp(arg, "--require")) {
            /* Skip -r MODULE for now (would need to preload) */
            optind += 2;
        } else if (!strcmp(arg, "--")) {
            optind++;
            break;
        } else if (arg[1] == '-') {
            /* Skip unknown --options silently (Node.js does this for many flags) */
            optind++;
        } else {
            break;
        }
    }

    /* Create runtime */
    rt = JS_NewRuntime();
    if (!rt) {
        fprintf(stderr, "node: cannot allocate JS runtime\n");
        return 2;
    }
    /* Note: do NOT call JS_SetMaxStackSize on wasm32. The shadow stack
       starts at a low address (~64KB), so subtracting any large stack_size
       wraps the uintptr_t stack_limit to a huge value, causing every
       js_check_stack_overflow to return true. Default stack_size=0 means
       no stack limit, same as the __wasi__ codepath. */

    js_std_set_worker_new_context_func(JS_NewNodeContext);
    js_std_init_handlers(rt);
    ctx = JS_NewNodeContext(rt);
    if (!ctx) {
        fprintf(stderr, "node: cannot allocate JS context\n");
        return 2;
    }

    /* Set up module loader for user ES modules. Custom normalize + loader
       give bare specifiers, `#imports`, and `node:foo` the Node-style
       resolution that npm's dynamic `import('chalk')` chain expects. */
    JS_SetModuleLoaderFunc2(rt, node_module_normalize, node_module_loader,
                            js_module_check_attributes, NULL);
    JS_SetHostPromiseRejectionTracker(rt, js_std_promise_rejection_tracker,
                                       NULL);

    /* Set up helpers (console, print, etc.) before bootstrap */
    js_std_add_helpers(ctx, argc - optind, argv + optind);

    /* Load the Node.js bootstrap (sets up require, process, Buffer, etc.) */
    js_std_eval_binary(ctx, qjsc_bootstrap, qjsc_bootstrap_size, 0);

    if (expr) {
        if (print_result) {
            /* -p: evaluate and print */
            char *wrapped;
            int len = strlen(expr) + 64;
            wrapped = malloc(len);
            snprintf(wrapped, len,
                     "process.stdout.write(String(eval(%s))+'\\n')",
                     expr);
            /* Use script eval so require() works */
            eval_buf(ctx, wrapped, strlen(wrapped), "<cmdline>", 0);
            free(wrapped);
        } else {
            /* -e: evaluate */
            int flags = module == 1 ? JS_EVAL_TYPE_MODULE : 0;
            eval_buf(ctx, expr, strlen(expr), "<cmdline>", flags);
        }
    } else if (optind < argc && !interactive) {
        /* Run script file */
        const char *filename = argv[optind];

        /* Set __filename and __dirname globals */
        JSValue global = JS_GetGlobalObject(ctx);
        char resolved[4096];
        if (filename[0] == '/') {
            strncpy(resolved, filename, sizeof(resolved) - 1);
        } else {
            char cwd[2048];
            if (getcwd(cwd, sizeof(cwd))) {
                snprintf(resolved, sizeof(resolved), "%s/%s", cwd, filename);
            } else {
                strncpy(resolved, filename, sizeof(resolved) - 1);
            }
        }
        resolved[sizeof(resolved) - 1] = '\0';
        JS_SetPropertyStr(ctx, global, "__filename",
                          JS_NewString(ctx, resolved));
        /* dirname */
        char *slash = strrchr(resolved, '/');
        if (slash) *slash = '\0';
        JS_SetPropertyStr(ctx, global, "__dirname",
                          JS_NewString(ctx, resolved));
        if (slash) *slash = '/'; /* restore */

        JS_FreeValue(ctx, global);

        if (eval_file(ctx, filename, module))
            goto fail;
    } else {
        /* Interactive REPL */
        interactive = 1;
    }

    if (interactive) {
        /* Use QuickJS REPL with Node.js globals available */
        JS_SetHostPromiseRejectionTracker(rt, NULL, NULL);
        js_std_eval_binary(ctx, qjsc_repl, qjsc_repl_size, 0);
    }

    r = js_node_loop(ctx);
    if (r) {
        js_std_dump_error(ctx);
        goto fail;
    }

    js_std_free_handlers(rt);
    JS_FreeContext(ctx);
    JS_FreeRuntime(rt);
    return 0;

fail:
    js_std_free_handlers(rt);
    JS_FreeContext(ctx);
    JS_FreeRuntime(rt);
    return 1;
}
