/*
 * Node.js-compatible CLI for QuickJS-NG
 *
 * This is NOT Node.js. It is a QuickJS-based runtime with a Node.js
 * compatibility layer that provides require(), process, Buffer, and
 * core Node.js modules (fs, path, events, os, util, stream, etc.).
 *
 * Based on qjs.c from QuickJS-NG.
 */
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>

#include "cutils.h"
#include "quickjs.h"
#include "quickjs-libc.h"

#include "node-compat-native/node-native.h"

/* Generated bytecode from node-compat/bootstrap.js */
extern const uint8_t qjsc_bootstrap[];
extern const uint32_t qjsc_bootstrap_size;

/* QuickJS built-in bytecodes */
extern const uint8_t qjsc_repl[];
extern const uint32_t qjsc_repl_size;

static int node__argc;
static char **node__argv;

static JSValue js_gc(JSContext *ctx, JSValueConst this_val,
                     int argc, JSValueConst *argv)
{
    JS_RunGC(JS_GetRuntime(ctx));
    return JS_UNDEFINED;
}

static const JSCFunctionListEntry global_obj[] = {
    JS_CFUNC_DEF("gc", 0, js_gc),
};

static JSContext *JS_NewNodeContext(JSRuntime *rt)
{
    JSContext *ctx;
    ctx = JS_NewContext(rt);
    if (!ctx)
        return NULL;

    /* Register QuickJS system modules (used by bootstrap) */
    js_init_module_std(ctx, "qjs:std");
    js_init_module_os(ctx, "qjs:os");
    js_init_module_bjson(ctx, "qjs:bjson");
    js_init_module_node_native(ctx, "qjs:node");

    JSValue global = JS_GetGlobalObject(ctx);
    JS_SetPropertyFunctionList(ctx, global, global_obj, countof(global_obj));

    /* Set up execArgv and argv0 for the bootstrap to pick up */
    JSValue args = JS_NewArray(ctx);
    for (int i = 0; i < node__argc; i++) {
        JS_SetPropertyUint32(ctx, args, i, JS_NewString(ctx, node__argv[i]));
    }
    JS_SetPropertyStr(ctx, global, "execArgv", args);
    JS_SetPropertyStr(ctx, global, "argv0",
                      JS_NewString(ctx, node__argv[0]));

    JS_FreeValue(ctx, global);
    return ctx;
}

static int eval_buf(JSContext *ctx, const void *buf, int buf_len,
                    const char *filename, int eval_flags)
{
    JSValue val;
    int ret;

    if ((eval_flags & JS_EVAL_TYPE_MASK) == JS_EVAL_TYPE_MODULE) {
        val = JS_Eval(ctx, buf, buf_len, filename,
                      eval_flags | JS_EVAL_FLAG_COMPILE_ONLY);
        if (!JS_IsException(val)) {
            js_module_set_import_meta(ctx, val, false, true);
            val = JS_EvalFunction(ctx, val);
        }
        val = js_std_await(ctx, val);
    } else {
        val = JS_Eval(ctx, buf, buf_len, filename, eval_flags);
    }
    if (JS_IsException(val)) {
        js_std_dump_error(ctx);
        ret = -1;
    } else {
        ret = 0;
    }
    JS_FreeValue(ctx, val);
    return ret;
}

static int eval_file(JSContext *ctx, const char *filename, int module)
{
    uint8_t *buf;
    int ret, eval_flags;
    size_t buf_len;

    buf = js_load_file(ctx, &buf_len, filename);
    if (!buf) {
        fprintf(stderr, "node: cannot load '%s': %s\n", filename, strerror(errno));
        return -1;
    }

    if (module < 0) {
        /* Auto-detect: .mjs = module, .cjs = script, else check content */
        module = (js__has_suffix(filename, ".mjs") ||
                  (!js__has_suffix(filename, ".cjs") &&
                   JS_DetectModule((const char *)buf, buf_len)));
    }

    if (module)
        eval_flags = JS_EVAL_TYPE_MODULE;
    else
        eval_flags = JS_EVAL_TYPE_GLOBAL;

    ret = eval_buf(ctx, buf, buf_len, filename, eval_flags);
    js_free(ctx, buf);
    return ret;
}

static void help(void)
{
    printf("node (QuickJS-NG v%s Node.js compatibility layer)\n"
           "This is NOT Node.js. It provides Node.js API compatibility\n"
           "via QuickJS-NG with POSIX os/std modules.\n"
           "\n"
           "usage: node [options] [script.js] [args...]\n"
           "       node -e 'code'       evaluate code\n"
           "       node -p 'expr'       evaluate and print\n"
           "       node --version       print version\n"
           "       node -h, --help      show help\n"
           "\n"
           "Supported Node.js modules:\n"
           "  assert, buffer, child_process, cluster, crypto, dns,\n"
           "  events, fs, http, https, module, net, os, path,\n"
           "  perf_hooks, punycode, querystring, readline, stream,\n"
           "  string_decoder, timers, tty, url, util, v8, vm,\n"
           "  worker_threads, zlib\n",
           JS_GetVersion());
    exit(0);
}

int main(int argc, char **argv)
{
    JSRuntime *rt;
    JSContext *ctx;
    int r = 0;
    int optind = 1;
    char *expr = NULL;
    int print_result = 0;
    int interactive = 0;
    int module = -1;

    node__argc = argc;
    node__argv = argv;

    /* Parse options */
    while (optind < argc && argv[optind][0] == '-') {
        const char *arg = argv[optind];

        if (!strcmp(arg, "-h") || !strcmp(arg, "--help")) {
            help();
        } else if (!strcmp(arg, "-v") || !strcmp(arg, "--version")) {
            printf("v22.0.0\n");
            return 0;
        } else if (!strcmp(arg, "-e") || !strcmp(arg, "--eval")) {
            optind++;
            if (optind >= argc) {
                fprintf(stderr, "node: missing argument for -e\n");
                return 1;
            }
            expr = argv[optind++];
            break;
        } else if (!strcmp(arg, "-p") || !strcmp(arg, "--print")) {
            optind++;
            if (optind >= argc) {
                fprintf(stderr, "node: missing argument for -p\n");
                return 1;
            }
            expr = argv[optind++];
            print_result = 1;
            break;
        } else if (!strcmp(arg, "-i") || !strcmp(arg, "--interactive")) {
            interactive = 1;
            optind++;
        } else if (!strcmp(arg, "--input-type=module")) {
            module = 1;
            optind++;
        } else if (!strcmp(arg, "-r") || !strcmp(arg, "--require")) {
            /* Skip -r MODULE for now (would need to preload) */
            optind += 2;
        } else if (!strcmp(arg, "--")) {
            optind++;
            break;
        } else if (arg[1] == '-') {
            /* Skip unknown --options silently (Node.js does this for many flags) */
            optind++;
        } else {
            break;
        }
    }

    /* Create runtime */
    rt = JS_NewRuntime();
    if (!rt) {
        fprintf(stderr, "node: cannot allocate JS runtime\n");
        return 2;
    }
    /* Note: do NOT call JS_SetMaxStackSize on wasm32. The shadow stack
       starts at a low address (~64KB), so subtracting any large stack_size
       wraps the uintptr_t stack_limit to a huge value, causing every
       js_check_stack_overflow to return true. Default stack_size=0 means
       no stack limit, same as the __wasi__ codepath. */

    js_std_set_worker_new_context_func(JS_NewNodeContext);
    js_std_init_handlers(rt);
    ctx = JS_NewNodeContext(rt);
    if (!ctx) {
        fprintf(stderr, "node: cannot allocate JS context\n");
        return 2;
    }

    /* Set up module loader for user ES modules */
    JS_SetModuleLoaderFunc2(rt, NULL, js_module_loader,
                            js_module_check_attributes, NULL);
    JS_SetHostPromiseRejectionTracker(rt, js_std_promise_rejection_tracker,
                                       NULL);

    /* Set up helpers (console, print, etc.) before bootstrap */
    js_std_add_helpers(ctx, argc - optind, argv + optind);

    /* Load the Node.js bootstrap (sets up require, process, Buffer, etc.) */
    js_std_eval_binary(ctx, qjsc_bootstrap, qjsc_bootstrap_size, 0);

    if (expr) {
        if (print_result) {
            /* -p: evaluate and print */
            char *wrapped;
            int len = strlen(expr) + 64;
            wrapped = malloc(len);
            snprintf(wrapped, len,
                     "process.stdout.write(String(eval(%s))+'\\n')",
                     expr);
            /* Use script eval so require() works */
            eval_buf(ctx, wrapped, strlen(wrapped), "<cmdline>", 0);
            free(wrapped);
        } else {
            /* -e: evaluate */
            int flags = module == 1 ? JS_EVAL_TYPE_MODULE : 0;
            eval_buf(ctx, expr, strlen(expr), "<cmdline>", flags);
        }
    } else if (optind < argc && !interactive) {
        /* Run script file */
        const char *filename = argv[optind];

        /* Set __filename and __dirname globals */
        JSValue global = JS_GetGlobalObject(ctx);
        char resolved[4096];
        if (filename[0] == '/') {
            strncpy(resolved, filename, sizeof(resolved) - 1);
        } else {
            char cwd[2048];
            if (getcwd(cwd, sizeof(cwd))) {
                snprintf(resolved, sizeof(resolved), "%s/%s", cwd, filename);
            } else {
                strncpy(resolved, filename, sizeof(resolved) - 1);
            }
        }
        resolved[sizeof(resolved) - 1] = '\0';
        JS_SetPropertyStr(ctx, global, "__filename",
                          JS_NewString(ctx, resolved));
        /* dirname */
        char *slash = strrchr(resolved, '/');
        if (slash) *slash = '\0';
        JS_SetPropertyStr(ctx, global, "__dirname",
                          JS_NewString(ctx, resolved));
        if (slash) *slash = '/'; /* restore */

        JS_FreeValue(ctx, global);

        if (eval_file(ctx, filename, module))
            goto fail;
    } else {
        /* Interactive REPL */
        interactive = 1;
    }

    if (interactive) {
        /* Use QuickJS REPL with Node.js globals available */
        JS_SetHostPromiseRejectionTracker(rt, NULL, NULL);
        js_std_eval_binary(ctx, qjsc_repl, qjsc_repl_size, 0);
    }

    r = js_std_loop(ctx);
    if (r) {
        js_std_dump_error(ctx);
        goto fail;
    }

    js_std_free_handlers(rt);
    JS_FreeContext(ctx);
    JS_FreeRuntime(rt);
    return 0;

fail:
    js_std_free_handlers(rt);
    JS_FreeContext(ctx);
    JS_FreeRuntime(rt);
    return 1;
}
