#!/usr/bin/env bash
# Build dinit (https://github.com/davmac314/dinit) for wasm32-posix.
# dinit is a service supervisor / init system. We use it as PID 1 in
# service-demo VFS images so the demos boot via real init mechanics
# (per-service config files, dependency resolution, fail-fast on
# upstream failures) rather than JS-side orchestration.
#
# Output: examples/libs/dinit/bin/dinit (and dinitctl, dinitcheck)
set -euo pipefail

DINIT_VERSION="${DINIT_VERSION:-v0.19.4}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
SYSROOT="$REPO_ROOT/sysroot"
SRC_DIR="$SCRIPT_DIR/dinit-src"
BIN_DIR="$SCRIPT_DIR/bin"

# --- Idempotent fast path ---
# If all three artifacts already exist (e.g. left over from a prior
# build, or downloaded by scripts/fetch-binaries.sh into bin/), just
# install them and return. This lets `xtask archive-stage` succeed in
# environments that don't have libc++ available — needed because the
# resolver invokes this script to ensure_built before staging.
if [ -f "$BIN_DIR/dinit.wasm" ] && [ -f "$BIN_DIR/dinitctl.wasm" ] && [ -f "$BIN_DIR/dinitcheck.wasm" ]; then
    echo "==> Reusing existing dinit artifacts in $BIN_DIR (skip rebuild)."
    source "$REPO_ROOT/scripts/install-local-binary.sh"
    install_local_binary dinit "$BIN_DIR/dinit.wasm" dinit.wasm
    install_local_binary dinit "$BIN_DIR/dinitctl.wasm" dinitctl.wasm
    install_local_binary dinit "$BIN_DIR/dinitcheck.wasm" dinitcheck.wasm
    exit 0
fi

# --- Prerequisites ---
if ! command -v wasm32posix-c++ &>/dev/null; then
    echo "ERROR: wasm32posix-c++ not found. Run 'npm link' in sdk/ first." >&2
    exit 1
fi

if [ ! -f "$SYSROOT/lib/libc++.a" ]; then
    echo "ERROR: libc++.a not found in $SYSROOT/lib/" >&2
    echo "       The MariaDB or another C++ build script installs it; build that first." >&2
    exit 1
fi

# --- Download source ---
if [ ! -d "$SRC_DIR" ]; then
    echo "==> Downloading dinit $DINIT_VERSION..."
    git clone --depth 1 --branch "$DINIT_VERSION" \
        https://github.com/davmac314/dinit.git "$SRC_DIR"
fi

cd "$SRC_DIR"

# --- Configure ---
# dinit's build is driven by mconfig (a make-included config file). We
# generate one by hand for the cross-compile rather than running
# ./configure (which probes the host system, not the wasm sysroot).
echo "==> Generating mconfig for wasm32-posix..."
cat > mconfig <<EOF
# Cross-compile config for wasm32-posix-kernel.
# Generated by build-dinit.sh; do not commit.

# Target toolchain (cross-compile to wasm32-posix)
CXX = wasm32posix-c++
CC = wasm32posix-cc

# Host toolchain — used by build/tools/mconfig-gen and any other
# generator binary that runs on the developer machine. The default
# c++ resolves to clang++ on macOS or g++ on Linux.
CXX_FOR_BUILD = c++
CXXFLAGS_FOR_BUILD = -std=c++14 -O1
CPPFLAGS_FOR_BUILD =
LDFLAGS_FOR_BUILD =

# Target flags. dinit uses C++ exceptions in its client code (dinitctl,
# dinit-monitor) so we cannot disable them. Add libc++ include path
# explicitly since the wasm32posix toolchain does not auto-include it;
# the library is picked up at link time via -lc++ -lc++abi.
CPPFLAGS = -D_POSIX_C_SOURCE=200809L -isystem $SYSROOT/include/c++/v1
CXXFLAGS = -std=c++14 -O2 -Wall -Wextra
CFLAGS = -O2 -Wall

# Link flags (target). Explicit -L because the SDK wrapper does not
# auto-add the sysroot lib path during link.
LDFLAGS_BASE = -L$SYSROOT/lib -lc++ -lc++abi

# Path/install
SBINDIR = /sbin
MANDIR = /usr/share/man

# Service defaults — the build Makefile passes these to mconfig-gen
# unconditionally. If empty, the generated #define expands to nothing
# at use sites, breaking compilation. Set them explicitly to dinit's
# documented defaults.
DEFAULT_AUTO_RESTART = ON_FAILURE
DEFAULT_START_TIMEOUT = 60
DEFAULT_STOP_TIMEOUT = 10

# dinit features
# Skip cgroup support (Linux-specific, not in wasm-posix-kernel).
SUPPORT_CGROUPS = 0
# Skip capability support (Linux-specific).
SUPPORT_CAPABILITIES = 0
# pselect-based event loop (most portable; epoll is Linux-only and we
# don't want to assume our wasm-kernel's epoll is feature-complete for
# dasynq's needs at this point).
USE_LIBSELECT_EV = 1
# No utmp updating (no wtmp/utmp in our environment).
DISABLE_UTMPX = 1

# Linker
LDFLAGS = \$(LDFLAGS_BASE)
EOF

# --- Build ---
echo "==> Building dinit (this may take a minute)..."
make clean 2>&1 | tail -5 || true
make -j"$(sysctl -n hw.ncpu 2>/dev/null || nproc)" 2>&1 | tail -30

# --- Collect binaries ---
echo "==> Collecting binaries..."
mkdir -p "$BIN_DIR"
for binary in dinit dinitctl dinitcheck; do
    if [ -f "src/$binary" ]; then
        cp "src/$binary" "$BIN_DIR/$binary.wasm"
        ls -la "$BIN_DIR/$binary.wasm"
    else
        echo "WARNING: src/$binary not found"
    fi
done

# --- Asyncify transform for fork support ---
# dinit forks once per service to launch each daemon (fork()+execvp()
# pattern). Without asyncify wrapping kernel_fork, the child wasm
# instance re-runs main() from scratch and always dispatches the FIRST
# service in dinit's start order — every fork's child ends up as the
# first service, no matter which service dinit thinks it's launching.
#
# The asyncify pass instruments callers up the chain to kernel_fork so
# the host can save/restore the call stack across fork: child resumes
# from the fork point with all locals intact, exec's the right binary.
# Same pattern as nginx/php-fpm/bash. Apply only to dinit (the only
# binary that forks); dinitctl and dinitcheck don't need it.
WASM_OPT="$(command -v wasm-opt 2>/dev/null || true)"
if [ -z "$WASM_OPT" ]; then
    echo "ERROR: wasm-opt not found. Install binaryen." >&2
    exit 1
fi

echo "==> Applying asyncify transform to dinit.wasm..."
"$WASM_OPT" --asyncify \
    --pass-arg="asyncify-imports@kernel.kernel_fork" \
    "$BIN_DIR/dinit.wasm" -o "$BIN_DIR/dinit.wasm"
ls -la "$BIN_DIR/dinit.wasm"

# Install into local-binaries/ so the resolver (host/src/binary-resolver.ts)
# picks these up over anything fetched by scripts/fetch-binaries.sh.
# Also makes the artifacts visible to `xtask archive-stage` when a
# package archive is being produced.
source "$REPO_ROOT/scripts/install-local-binary.sh"
install_local_binary dinit "$BIN_DIR/dinit.wasm" dinit.wasm
install_local_binary dinit "$BIN_DIR/dinitctl.wasm" dinitctl.wasm
install_local_binary dinit "$BIN_DIR/dinitcheck.wasm" dinitcheck.wasm

echo "==> dinit build complete"
