#!/usr/bin/env bash
set -euo pipefail

# Build bash 5.2 for wasm32-posix-kernel.
#
# Uses the SDK's wasm32posix-configure wrapper for cross-compilation.
# Applies asyncify with an onlylist so fork works (pipes, $(cmd), subshells).
#
# Output: examples/libs/bash/bin/bash.wasm

BASH_VERSION_PKG="${BASH_VERSION_PKG:-5.2.37}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
SRC_DIR="$SCRIPT_DIR/bash-src"
BIN_DIR="$SCRIPT_DIR/bin"
SYSROOT="$REPO_ROOT/sysroot"
ONLYLIST="$SCRIPT_DIR/asyncify-onlylist.txt"

# --- Prerequisites ---
if ! command -v wasm32posix-cc &>/dev/null; then
    echo "ERROR: wasm32posix-cc not found. Run 'npm link' in sdk/ first." >&2
    exit 1
fi

if [ ! -f "$SYSROOT/lib/libc.a" ]; then
    echo "ERROR: sysroot not found. Run: bash build.sh && bash scripts/build-musl.sh" >&2
    exit 1
fi

WASM_OPT="$(command -v wasm-opt 2>/dev/null || true)"
if [ -z "$WASM_OPT" ]; then
    echo "ERROR: wasm-opt not found. Install binaryen." >&2
    exit 1
fi

export WASM_POSIX_SYSROOT="$SYSROOT"
export WASM_POSIX_GLUE_DIR="$REPO_ROOT/glue"

# --- Download bash source ---
if [ ! -d "$SRC_DIR" ]; then
    echo "==> Downloading bash $BASH_VERSION_PKG..."
    TARBALL="bash-${BASH_VERSION_PKG}.tar.gz"
    URL="https://ftp.gnu.org/gnu/bash/${TARBALL}"
    curl -fsSL "$URL" -o "/tmp/$TARBALL"
    mkdir -p "$SRC_DIR"
    tar xzf "/tmp/$TARBALL" -C "$SRC_DIR" --strip-components=1
    rm "/tmp/$TARBALL"
    echo "==> Source extracted to $SRC_DIR"
fi

cd "$SRC_DIR"

# --- Configure ---
if [ ! -f Makefile ]; then
    echo "==> Configuring bash for wasm32..."

    # Most cache variables come from sdk/config.site via wasm32posix-configure.
    # Only override bash-specific cache here.

    # Bash-specific cache — configure probes these with runtime tests we can't execute
    export bash_cv_dup2_broken=no
    export bash_cv_pgrp_pipe=no
    export bash_cv_sys_siglist=no
    export bash_cv_under_sys_siglist=no
    export bash_cv_getenv_redef=yes
    export bash_cv_printf_a_format=yes
    export bash_cv_mail_dir=/var/mail
    export bash_cv_func_sigsetjmp=present
    export bash_cv_func_strcoll_broken=no
    export bash_cv_must_reinstall_sighandlers=no
    export bash_cv_job_control_missing=present
    export bash_cv_sys_named_pipes=present
    export bash_cv_unusable_rtsigs=no
    export bash_cv_type_rlimit=quad_t
    export bash_cv_wcontinued_broken=no
    export bash_cv_fpurge_missing=yes
    export bash_cv_fnmatch_equiv_fallback=yes
    export bash_cv_sys_errlist=yes
    export bash_cv_func_strcasestr=yes
    export bash_cv_getcwd_malloc=yes
    export bash_cv_mkfifo_supported=yes
    export bash_cv_termcap_lib=libtinfo
    export bash_cv_struct_timespec_in_time_h=yes
    export bash_cv_struct_stat_st_atim_tv_nsec=yes
    export bash_cv_dev_fd=absent
    export bash_cv_dev_stdin=absent

    # Functions bash probes for that musl provides but the SDK config.site doesn't cover
    export ac_cv_func_getwd=no
    export ac_cv_func_sigrelse=no
    export ac_cv_func_ulimit=no
    export ac_cv_func_fpurge=no
    export ac_cv_func___fpurge=yes

    # glibc extensions not in musl — bash's configure wrongly detects them as
    # present when cross-compiling without link tests. Force bash to use its
    # own fallback implementations (shipped in lib/sh/).
    export ac_cv_func_mbschr=no
    export ac_cv_func_mbsnrtowcs=no
    export ac_cv_func_wcsnrtombs=no
    export ac_cv_func_fgets_unlocked=no
    export ac_cv_func_fputs_unlocked=no
    export ac_cv_func_getc_unlocked=no
    export ac_cv_func_getchar_unlocked=no
    export ac_cv_func_putc_unlocked=no
    export ac_cv_func_putchar_unlocked=no

    # -gline-tables-only preserves function names for asyncify-onlylist.
    export CFLAGS="-O2 -gline-tables-only -Wno-implicit-function-declaration -Wno-int-conversion -Wno-incompatible-pointer-types"
    export LDFLAGS="-Wl,-z,stack-size=1048576"

    # --disable-bang-history is required: BANG_HISTORY implies HISTORY via
    # config-bot.h, which re-enables bashhist.c. TODO: enable readline+history
    # once wasm32 call_indirect signature issues in readline are resolved.
    wasm32posix-configure \
        --prefix=/usr \
        --without-bash-malloc \
        --disable-readline \
        --disable-history \
        --disable-bang-history \
        --without-curses \
        --disable-nls \
        --disable-mem-scramble \
        --disable-net-redirections \
        --disable-progcomp \
        2>&1 | tail -30

    echo "==> Configure complete."
fi

# --- Patch host-generated files ---
# signames.c is generated by mksignames (host binary) using the build host's
# signal numbers. On macOS, SIGUSR1=30, but on Linux/wasm32 SIGUSR1=10.
# Regenerating after build is too late — signames.c is compiled in.
if [ -f support/signames.c ] || [ -f signames.c ]; then
    echo "==> Patching signal names for Linux/wasm32..."
    # Will be regenerated during make; we patch post-gen below
fi

# --- wasm32 function pointer signature fix ---
# Bash's unwind_prot system stores cleanup functions as `Function *` (typedef'd
# as `int Function()` — K&R no-args). On wasm32, call_indirect requires exact
# signature match; x86/ARM ABIs tolerate mismatch. Most cleanups are
# `void (*)(void *)`. The no-arg ones trap with "indirect call type mismatch".
#
# Fix 1: patch unwind_frame_run_internal to cast cleanup to (void(*)(void*))
# Fix 2: patch the no-arg cleanup functions (pop_stream, parser_restore_alias)
#        to accept an unused void* arg so their wasm signature matches
if ! grep -q "wasm32 signature fix" unwind_prot.c; then
    echo "==> Patching unwind_prot.c: cast cleanup to void(*)(void*) for wasm32"
    # Cast the cleanup call to the correct signature
    perl -i -pe 's/\Q(*(elt->head.cleanup)) (elt->arg.v);\E/\/\* wasm32 signature fix: cleanups are always void (*)(void *) *\/\n\t    ((void (*)(void *))(elt->head.cleanup)) (elt->arg.v);/' unwind_prot.c
fi

# Inject wrapper functions for no-arg cleanup functions. On wasm32 the unwind
# dispatch expects `void (*)(void *)`; functions like pop_stream/parser_restore_alias
# that take no args don't match. Wrappers bridge the signatures without touching
# the generated parser.
if ! grep -q "wasm32_unwind_wrappers" builtins/evalstring.c; then
    echo "==> Injecting wasm32 unwind wrappers into evalstring.c"
    cat > /tmp/bash-wrappers.txt << 'WRAPEOF'
/* wasm32_unwind_wrappers: bridge no-arg cleanups to void(*)(void*) signature */
extern void pop_stream (void);
extern void parser_restore_alias (void);
static void pop_stream_w (void *unused) { pop_stream (); }
static void parser_restore_alias_w (void *unused) { parser_restore_alias (); }
WRAPEOF
    # Insert wrappers after the last "common.h" include (stable insertion point
    # before any function definitions).
    awk '
      /^#include "common\.h"/ && !done {
        print;
        while ((getline line < "/tmp/bash-wrappers.txt") > 0) print line;
        close("/tmp/bash-wrappers.txt");
        done = 1;
        next;
      }
      { print }
    ' builtins/evalstring.c > builtins/evalstring.c.new && mv builtins/evalstring.c.new builtins/evalstring.c
    # Replace cleanup function names with wrapper names at add_unwind_protect call sites
    perl -i -pe 's/add_unwind_protect \(pop_stream,/add_unwind_protect (pop_stream_w,/g' builtins/evalstring.c
    perl -i -pe 's/add_unwind_protect \(parser_restore_alias,/add_unwind_protect (parser_restore_alias_w,/g' builtins/evalstring.c
    if ! grep -q "pop_stream_w" builtins/evalstring.c; then
        echo "ERROR: wrapper injection into evalstring.c failed" >&2
        exit 1
    fi
fi

# --- Patch Makefile: strip libhistory from link ---
# --disable-history unsets HISTORY in config.h but the Makefile still sets
# HISTORY_LIB=-lhistory. libhistory.a contains xmalloc/shell.o duplicates of
# bash's own sources. Drop it from the link line.
if grep -q '^HISTORY_LIB = -lhistory' Makefile; then
    sed -i.bak 's/^HISTORY_LIB = -lhistory/HISTORY_LIB =/' Makefile
    rm -f Makefile.bak
    echo "==> Patched Makefile: HISTORY_LIB unset for link"
fi

# --- Provide __main_argc_argv wrapper ---
# Clang for wasm32 auto-renames `int main(int, char**)` -> __main_argc_argv
# so the CRT can call it. Bash uses K&R-style `main(argc, argv, env)` with
# three args, which clang does NOT auto-mangle. Without the wrapper, wasm-ld
# GC-strips all bash code because nothing reaches `main` from `_start`.
cat > main_wrapper.c << 'WRAPEOF'
extern int main(int argc, char **argv, char **envp);
extern char **environ;
int __main_argc_argv(int argc, char **argv) {
    return main(argc, argv, environ);
}
WRAPEOF

# Inject main_wrapper.o into the bash link line
if ! grep -q "main_wrapper.o" Makefile; then
    # OBJECTS line has tabs; match any whitespace before =
    sed -i.bak 's/^\(OBJECTS[[:space:]]*=[[:space:]]*\)shell\.o /\1main_wrapper.o shell.o /' Makefile
    rm -f Makefile.bak
    if grep -q "main_wrapper.o" Makefile; then
        echo "==> Injected main_wrapper.o into OBJECTS"
    else
        echo "ERROR: failed to inject main_wrapper.o into Makefile" >&2
        exit 1
    fi
fi

# --- Build ---
echo "==> Building bash..."
make -j"$(sysctl -n hw.ncpu 2>/dev/null || nproc)" 2>&1 | tail -30

BASH_BIN="$SRC_DIR/bash"
if [ ! -f "$BASH_BIN" ]; then
    echo "ERROR: bash binary not found after build" >&2
    exit 1
fi

mkdir -p "$BIN_DIR"
cp "$BASH_BIN" "$BIN_DIR/bash.wasm"
SIZE_BEFORE=$(wc -c < "$BIN_DIR/bash.wasm" | tr -d ' ')
echo "==> Pre-asyncify size: $(echo "$SIZE_BEFORE" | numfmt --to=iec 2>/dev/null || echo "${SIZE_BEFORE} bytes")"

# --- Asyncify transform with onlylist ---
if [ -f "$ONLYLIST" ]; then
    echo "==> Applying asyncify with onlylist..."
    ONLY_FUNCS=$(grep -v '^#' "$ONLYLIST" | grep -v '^\s*$' | tr -d ' ' | tr '\n' ',' | sed 's/,$//')

    "$WASM_OPT" -g --asyncify \
        --pass-arg="asyncify-imports@kernel.kernel_fork" \
        --pass-arg="asyncify-onlylist@${ONLY_FUNCS}" \
        "$BIN_DIR/bash.wasm" -o "$BIN_DIR/bash.wasm"

    "$WASM_OPT" -O2 "$BIN_DIR/bash.wasm" -o "$BIN_DIR/bash.wasm"
fi

SIZE_AFTER=$(wc -c < "$BIN_DIR/bash.wasm" | tr -d ' ')
echo "==> Final size: $(echo "$SIZE_AFTER" | numfmt --to=iec 2>/dev/null || echo "${SIZE_AFTER} bytes")"

echo ""
echo "==> bash built successfully!"
echo "Binary: $BIN_DIR/bash.wasm"
echo ""
echo "Run with:"
echo "  npx tsx examples/shell/serve.ts -c 'echo hello from bash'"
