/* GENERATED by `cargo xtask dump-abi`. Do not edit by hand. */
/* Regenerated by scripts/check-abi-version.sh; drift is a CI failure. */
#ifndef WASM_POSIX_ABI_CONSTANTS_H
#define WASM_POSIX_ABI_CONSTANTS_H

/* Mirrors wasm_posix_shared::ABI_VERSION. */
#define WASM_POSIX_ABI_VERSION 11u

#endif /* WASM_POSIX_ABI_CONSTANTS_H */
