#!/usr/bin/env bash
#
# Publish a per-PR staging release to GitHub. Mirrors
# scripts/publish-release.sh but targets a `pr-<NNN>-staging`
# pre-release tag. Idempotent: re-running on the same PR with new
# bytes uses --clobber to replace assets in-place.
#
# Usage:
#   scripts/publish-pr-staging.sh --pr <N> --staging <dir>
#
# Prerequisites:
#   - `gh` and `jq` CLIs on PATH; `gh` authenticated against the
#     upstream repo.
#   - Staging directory already populated by
#     `scripts/stage-pr-staging.sh`, including manifest.json,
#     binaries.lock.pr, and the {libs,programs}/ subdirectories.
#   - The staged manifest's release_tag must equal `pr-<N>-staging`
#     and the overlay's staging_tag must match. Drift fails fast.
#
# Exit codes:
#   0  published successfully (or skipped — empty staging)
#   1  setup error
#   2  bad arguments / missing prerequisite tool

set -euo pipefail

PR=""
STAGING=""

while [ $# -gt 0 ]; do
    case "$1" in
        --pr)      PR="$2"; shift 2 ;;
        --staging) STAGING="$2"; shift 2 ;;
        -h|--help)
            sed -n '3,23p' "$0"
            exit 0
            ;;
        *) echo "unknown arg $1" >&2; exit 2 ;;
    esac
done

[ -n "$PR" ]      || { echo "--pr <N> is required" >&2; exit 2; }
[ -n "$STAGING" ] || { echo "--staging <dir> is required (run scripts/stage-pr-staging.sh first)" >&2; exit 2; }
case "$PR" in
    ''|*[!0-9]*) echo "--pr must be a positive integer (got: $PR)" >&2; exit 2 ;;
esac

for tool in gh jq; do
    command -v "$tool" >/dev/null 2>&1 || {
        echo "ERROR: $tool not found on PATH" >&2
        exit 2
    }
done

[ -d "$STAGING" ] || { echo "staging dir $STAGING does not exist" >&2; exit 1; }
[ -f "$STAGING/manifest.json" ]    || { echo "staging dir $STAGING missing manifest.json" >&2; exit 1; }
[ -f "$STAGING/binaries.lock.pr" ] || { echo "staging dir $STAGING missing binaries.lock.pr" >&2; exit 1; }

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

TAG="pr-${PR}-staging"

# Cross-check tag agreement. Same rationale as publish-release.sh's
# guard: prevent silent drift between the manifest's release_tag, the
# overlay's staging_tag, and the GitHub tag we're about to create.
manifest_tag=$(jq -r .release_tag "$STAGING/manifest.json" 2>/dev/null || echo "<unparseable>")
overlay_tag=$(jq -r .staging_tag "$STAGING/binaries.lock.pr" 2>/dev/null || echo "<unparseable>")
if [ "$manifest_tag" != "$TAG" ]; then
    echo "ERROR: manifest release_tag=$manifest_tag does not match expected $TAG" >&2
    exit 1
fi
if [ "$overlay_tag" != "$TAG" ]; then
    echo "ERROR: overlay staging_tag=$overlay_tag does not match expected $TAG" >&2
    exit 1
fi

OVERRIDE_COUNT=$(jq '.overrides | length' "$STAGING/binaries.lock.pr")
if [ "$OVERRIDE_COUNT" = "0" ]; then
    echo "publish-pr-staging: empty overlay (no cache_key_sha changed in this push) — nothing to publish."
    echo "  Existing $TAG release (if any) remains valid."
    exit 0
fi

# Build the asset list: manifest + overlay + every archive.
assets=()
while IFS= read -r -d '' f; do
    assets+=("$f")
done < <(
    {
        find "$STAGING" -maxdepth 1 -type f -print0
        find "$STAGING/libs" -maxdepth 1 -type f -print0 2>/dev/null
        find "$STAGING/programs" -maxdepth 1 -type f -print0 2>/dev/null
    } | sort -z
)

[ "${#assets[@]}" -gt 0 ] || { echo "ERROR: no assets to upload" >&2; exit 1; }

echo "== Publishing $TAG with ${#assets[@]} asset(s) =="
for a in "${assets[@]}"; do
    # `wc -c < <file>` is portable across BSD and GNU coreutils;
    # `stat -f %z` (BSD) collides with GNU stat's `-f` syntax inside
    # the Nix dev shell.
    size=$(wc -c < "$a" | tr -d ' ')
    printf "  %10s  %s\n" "$size" "$(basename "$a")"
done

if [ "${DRY_RUN:-0}" = "1" ]; then
    echo
    echo "DRY_RUN=1 — stopping before gh release."
    exit 0
fi

# Idempotent publish: clobber existing assets if the release is
# already there (re-runs from later pushes), otherwise create fresh.
HEAD_SHA=$(git rev-parse HEAD)
if gh release view "$TAG" >/dev/null 2>&1; then
    echo "release $TAG already exists; replacing assets in-place"
    gh release upload "$TAG" --clobber "${assets[@]}"
else
    echo "creating new pre-release $TAG (target: $HEAD_SHA)"
    gh release create "$TAG" \
        --prerelease \
        --target "$HEAD_SHA" \
        --title "PR #$PR staging build" \
        --notes "Per-PR staging build. Generated by scripts/publish-pr-staging.sh from PR #$PR. See docs/binary-releases.md (PR-staging overlay section). Deleted automatically on PR close." \
        "${assets[@]}"
fi

echo
echo "Published: https://github.com/brandonpayton/wasm-posix-kernel/releases/tag/$TAG"

# Post-upload verification — see publish-release.sh for the rationale.
# Verify against the LOCAL staging dir (whose bytes we just uploaded),
# not via --tag. The GitHub release CDN serves cached assets for
# several minutes after a fresh upload; verifying the live tag
# straight after the publish would routinely false-positive.
echo
echo "Verifying release consistency (local manifest + staging dir)..."
"$REPO_ROOT/scripts/verify-release.sh" \
    --manifest "$STAGING/manifest.json" \
    --archive-base "$STAGING"
