//! Regenerate `abi/snapshot.json` from authoritative sources.
//!
//! Sources (all compiled into this binary via the `wasm_posix_shared` crate):
//!
//!   * [`wasm_posix_shared::ABI_VERSION`] — the integer version number
//!   * [`wasm_posix_shared::Syscall`] — named syscall number table
//!   * [`wasm_posix_shared::channel`] — channel header byte layout
//!   * Marshalled repr(C) structs — offsets via `core::mem::offset_of!`
//!   * [`wasm_posix_shared::abi`] — asyncify save slots, global names,
//!     custom-section name
//!
//! When `--kernel-wasm <path>` is provided, the snapshot also covers
//! every export in the built kernel `.wasm` (after filtering through
//! `shared::abi::export_is_tracked` to drop toolchain implementation
//! details). Function signatures are recorded, as are the types and
//! mutability of globals; for globals matching
//! `shared::abi::ABI_VALUE_CAPTURE_PREFIXES` the initial value is
//! captured too.
//!
//! CI is expected to build the kernel first and pass `--kernel-wasm`.
//! If the flag is omitted, `dump-abi` fails loudly rather than writing
//! a partial snapshot — a quietly-thinner snapshot would silently
//! defeat the check.

use std::collections::BTreeMap;
use std::mem::{offset_of, size_of};
use std::path::PathBuf;

use serde_json::{json, Value};
use wasm_posix_shared as shared;

use crate::{repo_root, JsonMap};

pub fn run(args: Vec<String>) -> Result<(), String> {
    let mut out_path: Option<PathBuf> = None;
    let mut kernel_wasm: Option<PathBuf> = None;
    let mut check = false;

    let mut it = args.into_iter();
    while let Some(a) = it.next() {
        match a.as_str() {
            "--out" => out_path = Some(it.next().ok_or("--out requires a path")?.into()),
            "--kernel-wasm" => {
                kernel_wasm = Some(it.next().ok_or("--kernel-wasm requires a path")?.into())
            }
            "--check" => check = true,
            other => return Err(format!("unknown arg {other:?}")),
        }
    }

    let kernel_wasm = kernel_wasm.ok_or_else(|| {
        "missing --kernel-wasm <path>. Build the kernel first \
         (e.g. via scripts/check-abi-version.sh) and pass the path to \
         target/wasm64-unknown-unknown/release/wasm_posix_kernel.wasm. \
         Refusing to write a partial snapshot."
            .to_string()
    })?;

    let snapshot = build_snapshot(&kernel_wasm)?;
    let rendered = render_deterministic(&snapshot);
    let header = render_c_header();

    let out = out_path.unwrap_or_else(|| repo_root().join("abi/snapshot.json"));
    let header_out = repo_root().join("glue/abi_constants.h");

    if check {
        check_file(&out, &rendered, "ABI snapshot")?;
        check_file(&header_out, &header, "glue/abi_constants.h")?;
        println!("abi snapshot up-to-date: {}", out.display());
        println!("abi header up-to-date:  {}", header_out.display());
        return Ok(());
    }

    write_file(&out, &rendered)?;
    println!("wrote {}", out.display());
    write_file(&header_out, &header)?;
    println!("wrote {}", header_out.display());
    Ok(())
}

fn check_file(path: &std::path::Path, expected: &str, label: &str) -> Result<(), String> {
    let existing = std::fs::read_to_string(path)
        .map_err(|e| format!("read {}: {e}", path.display()))?;
    if existing != expected {
        eprintln!(
            "{label} at {} is out of date.\n\
             Run `bash scripts/check-abi-version.sh update` to regenerate,\n\
             and bump `ABI_VERSION` in crates/shared/src/lib.rs if the\n\
             contract actually changed.",
            path.display()
        );
        return Err(format!("{label} drift"));
    }
    Ok(())
}

fn write_file(path: &std::path::Path, contents: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("mkdir {}: {e}", parent.display()))?;
    }
    std::fs::write(path, contents)
        .map_err(|e| format!("write {}: {e}", path.display()))
}

/// C header consumed by `glue/channel_syscall.c` and any other C code
/// that needs to agree with Rust on ABI-surface constants.
fn render_c_header() -> String {
    format!(
        "/* GENERATED by `cargo xtask dump-abi`. Do not edit by hand. */\n\
         /* Regenerated by scripts/check-abi-version.sh; drift is a CI failure. */\n\
         #ifndef WASM_POSIX_ABI_CONSTANTS_H\n\
         #define WASM_POSIX_ABI_CONSTANTS_H\n\
         \n\
         /* Mirrors wasm_posix_shared::ABI_VERSION. */\n\
         #define WASM_POSIX_ABI_VERSION {version}u\n\
         \n\
         #endif /* WASM_POSIX_ABI_CONSTANTS_H */\n",
        version = shared::ABI_VERSION
    )
}

/// Collect per-field (name, offset) from a repr(C) struct using
/// `offset_of!` and hand off to [`build_struct_layout`] for size
/// computation + JSON rendering.
macro_rules! struct_layout {
    ($ty:ty { $($field:ident),* $(,)? }) => {{
        let size = size_of::<$ty>();
        let fields: Vec<(&'static str, usize)> = vec![
            $((stringify!($field), offset_of!($ty, $field))),*
        ];
        build_struct_layout(size, fields)
    }};
}

fn build_struct_layout(total_size: usize, fields: Vec<(&'static str, usize)>) -> Value {
    // Emit (offset, span) per field where span = bytes until the next
    // field's offset (or end of struct). Span includes trailing alignment
    // padding, so any ABI-relevant shift in layout — reordering, type
    // size change, or padding change — shows up as a changed span.
    let mut sorted_offsets: Vec<usize> = fields.iter().map(|(_, o)| *o).collect();
    sorted_offsets.sort();
    sorted_offsets.dedup();

    let mut field_jsons = Vec::with_capacity(fields.len());
    for (name, off) in &fields {
        let idx = sorted_offsets.binary_search(off).expect("offset present");
        let next = sorted_offsets.get(idx + 1).copied().unwrap_or(total_size);
        let span = next - off;
        let mut m: JsonMap = BTreeMap::new();
        m.insert("name".into(), json!(name));
        m.insert("offset".into(), json!(off));
        m.insert("span".into(), json!(span));
        field_jsons.push(Value::Object(m.into_iter().collect()));
    }
    let mut m: JsonMap = BTreeMap::new();
    m.insert("size".into(), json!(total_size));
    m.insert("fields".into(), Value::Array(field_jsons));
    Value::Object(m.into_iter().collect())
}

fn build_snapshot(kernel_wasm: &std::path::Path) -> Result<JsonMap, String> {
    let mut root: JsonMap = BTreeMap::new();

    root.insert("abi_version".into(), json!(shared::ABI_VERSION));

    root.insert("channel_header".into(), channel_header());
    root.insert("channel_signal_area".into(), channel_signal_area());
    root.insert("channel_buffers".into(), channel_buffers());

    root.insert("marshalled_structs".into(), marshalled_structs());
    root.insert("syscalls".into(), syscalls());
    root.insert("channel_status_codes".into(), channel_status_codes());
    root.insert("asyncify_save_slots".into(), asyncify_save_slots());
    root.insert("custom_sections".into(), custom_sections());
    root.insert("process_expected_globals".into(), process_expected_globals());

    root.insert("export_deny".into(), export_deny());

    let wasm = std::fs::read(kernel_wasm)
        .map_err(|e| format!("read {}: {e}", kernel_wasm.display()))?;
    root.insert("kernel_exports".into(), kernel_exports(&wasm)?);

    Ok(root)
}

fn channel_header() -> Value {
    use shared::channel::*;
    // The field list is hand-authored; offsets below are read from the
    // actual shared:: constants that kernel and glue reference, so the
    // hand-authored table cannot silently drift from them.
    let fields = [
        ("status", STATUS_OFFSET, 4usize, "i32"),
        ("syscall", SYSCALL_OFFSET, 4, "i32"),
        ("args", ARGS_OFFSET, ARGS_COUNT * ARG_SIZE, "[i64; 6]"),
        ("ret", RETURN_OFFSET, 8, "i64"),
        ("errno", ERRNO_OFFSET, 4, "i32"),
    ];

    let mut covered: usize = 0;
    let fields_json: Vec<Value> = fields
        .iter()
        .map(|(name, offset, size, ty)| {
            assert!(
                *offset >= covered,
                "channel header field {name:?} overlaps previous ({offset} < {covered})"
            );
            covered = offset + size;
            let mut m: JsonMap = BTreeMap::new();
            m.insert("name".into(), json!(name));
            m.insert("offset".into(), json!(offset));
            m.insert("size".into(), json!(size));
            m.insert("type".into(), json!(ty));
            Value::Object(m.into_iter().collect())
        })
        .collect();

    assert!(
        covered <= HEADER_SIZE,
        "channel header fields overrun HEADER_SIZE ({covered} > {HEADER_SIZE})"
    );

    let mut m: JsonMap = BTreeMap::new();
    m.insert("size".into(), json!(HEADER_SIZE));
    m.insert("fields".into(), Value::Array(fields_json));
    Value::Object(m.into_iter().collect())
}

fn channel_buffers() -> Value {
    use shared::channel::*;
    let mut m: JsonMap = BTreeMap::new();
    m.insert("data_offset".into(), json!(DATA_OFFSET));
    m.insert("data_size".into(), json!(DATA_SIZE));
    m.insert("min_channel_size".into(), json!(MIN_CHANNEL_SIZE));
    Value::Object(m.into_iter().collect())
}

fn channel_signal_area() -> Value {
    use shared::channel::*;
    let entries = [
        ("SIG_SIGNUM", SIG_SIGNUM, 4u32, "u32, signal number (0=none)"),
        ("SIG_HANDLER", SIG_HANDLER, 4, "u32, handler table index"),
        ("SIG_FLAGS", SIG_FLAGS, 4, "u32, sa_flags"),
        ("SIG_OLD_MASK", SIG_OLD_MASK, 8, "u64 (LE), saved blocked mask"),
    ];
    let mut list = Vec::new();
    for (name, offset, size, meaning) in entries {
        let mut m: JsonMap = BTreeMap::new();
        m.insert("name".into(), json!(name));
        m.insert("offset".into(), json!(offset));
        m.insert("size".into(), json!(size));
        m.insert("meaning".into(), json!(meaning));
        list.push(Value::Object(m.into_iter().collect()));
    }
    let mut m: JsonMap = BTreeMap::new();
    m.insert("base".into(), json!(SIG_BASE));
    m.insert("slots".into(), Value::Array(list));
    Value::Object(m.into_iter().collect())
}

fn marshalled_structs() -> Value {
    use shared::{WasmDirent, WasmFlock, WasmPollFd, WasmStat, WasmStatfs, WasmTimespec};

    let mut structs: JsonMap = BTreeMap::new();
    structs.insert(
        "WasmStat".into(),
        struct_layout!(WasmStat {
            st_dev, st_ino, st_mode, st_nlink, st_uid, st_gid, st_size,
            st_atime_sec, st_atime_nsec,
            st_mtime_sec, st_mtime_nsec,
            st_ctime_sec, st_ctime_nsec,
            _pad,
        }),
    );
    structs.insert(
        "WasmDirent".into(),
        struct_layout!(WasmDirent { d_ino, d_type, d_namlen }),
    );
    structs.insert(
        "WasmFlock".into(),
        struct_layout!(WasmFlock { l_type, l_whence, _pad1, l_start, l_len, l_pid, _pad2 }),
    );
    structs.insert(
        "WasmTimespec".into(),
        struct_layout!(WasmTimespec { tv_sec, tv_nsec }),
    );
    structs.insert(
        "WasmPollFd".into(),
        struct_layout!(WasmPollFd { fd, events, revents }),
    );
    structs.insert(
        "WasmStatfs".into(),
        struct_layout!(WasmStatfs {
            f_type, f_bsize, f_blocks, f_bfree, f_bavail, f_files, f_ffree,
            f_fsid, f_namelen, f_frsize, f_flags, _pad,
        }),
    );

    Value::Object(structs.into_iter().collect())
}

fn syscalls() -> Value {
    // Walk 0..1024 and collect every number the Syscall enum names.
    // Gaps (numbers handled in wasm_api.rs dispatch but not named in the
    // enum) are intentionally NOT in scope for this snapshot — they are
    // tracked by a follow-up change that moves all syscall numbers into
    // the enum as the single source of truth.
    let mut list = Vec::new();
    for n in 0u32..1024 {
        if let Some(s) = shared::Syscall::from_u32(n) {
            let mut m: JsonMap = BTreeMap::new();
            m.insert("number".into(), json!(n));
            m.insert("name".into(), json!(format!("{s:?}")));
            list.push(Value::Object(m.into_iter().collect()));
        }
    }
    Value::Array(list)
}

fn channel_status_codes() -> Value {
    use shared::ChannelStatus::*;
    let mut list = Vec::new();
    for (n, name) in [
        (Idle, "Idle"),
        (Pending, "Pending"),
        (Complete, "Complete"),
        (Error, "Error"),
    ] {
        let mut m: JsonMap = BTreeMap::new();
        m.insert("number".into(), json!(n as u32));
        m.insert("name".into(), json!(name));
        list.push(Value::Object(m.into_iter().collect()));
    }
    Value::Array(list)
}

fn asyncify_save_slots() -> Value {
    let mut list = Vec::new();
    for slot in shared::abi::ASYNCIFY_SAVE_SLOTS {
        let mut m: JsonMap = BTreeMap::new();
        m.insert("name".into(), json!(slot.name));
        m.insert("meaning".into(), json!(slot.meaning));
        m.insert("offset_wasm32".into(), json!(slot.offset_wasm32));
        m.insert("offset_wasm64".into(), json!(slot.offset_wasm64));
        m.insert("width_wasm32".into(), json!(slot.width_wasm32));
        m.insert("width_wasm64".into(), json!(slot.width_wasm64));
        list.push(Value::Object(m.into_iter().collect()));
    }
    Value::Array(list)
}

fn custom_sections() -> Value {
    json!([shared::abi::ABI_CUSTOM_SECTION])
}

fn process_expected_globals() -> Value {
    let mut list: Vec<&str> = shared::abi::PROCESS_EXPECTED_GLOBALS.to_vec();
    list.sort();
    Value::Array(list.into_iter().map(Value::from).collect())
}

fn export_deny() -> Value {
    let mut prefixes: Vec<&str> = shared::abi::EXPORT_DENY_PREFIXES.to_vec();
    let mut exact: Vec<&str> = shared::abi::EXPORT_DENY_EXACT.to_vec();
    let mut value_prefixes: Vec<&str> = shared::abi::ABI_VALUE_CAPTURE_PREFIXES.to_vec();
    prefixes.sort();
    exact.sort();
    value_prefixes.sort();
    let mut m: JsonMap = BTreeMap::new();
    m.insert(
        "deny_prefixes".into(),
        Value::Array(prefixes.into_iter().map(Value::from).collect()),
    );
    m.insert(
        "deny_exact".into(),
        Value::Array(exact.into_iter().map(Value::from).collect()),
    );
    m.insert(
        "value_capture_prefixes".into(),
        Value::Array(value_prefixes.into_iter().map(Value::from).collect()),
    );
    Value::Object(m.into_iter().collect())
}

fn kernel_exports(bytes: &[u8]) -> Result<Value, String> {
    use wasmparser::{
        CompositeInnerType, ExternalKind, FuncType, GlobalType, Imports, Operator, Parser,
        Payload, TypeRef,
    };

    // Accumulate what we need to resolve exports. Wasm section ordering
    // puts types, imports, functions, globals before exports, so a
    // single forward pass is sufficient.
    let mut func_type_for_local_idx: Vec<u32> = Vec::new();
    let mut func_types: Vec<FuncType> = Vec::new();
    let mut imported_funcs: u32 = 0;
    let mut imported_globals: u32 = 0;
    let mut global_types: Vec<GlobalType> = Vec::new();
    let mut global_init_i64: Vec<Option<i64>> = Vec::new();
    let mut exports: Vec<(String, ExternalKind, u32)> = Vec::new();

    for payload in Parser::new(0).parse_all(bytes) {
        let p = payload.map_err(|e| format!("parse wasm: {e}"))?;
        match p {
            Payload::TypeSection(r) => {
                for rec in r {
                    let rec = rec.map_err(|e| format!("type section: {e}"))?;
                    for st in rec.types() {
                        match &st.composite_type.inner {
                            CompositeInnerType::Func(f) => func_types.push(f.clone()),
                            // Non-func composite types (arrays/structs from
                            // the GC proposal) are not in scope here; push
                            // a zero-arity placeholder so index arithmetic
                            // stays correct.
                            _ => func_types.push(FuncType::new([], [])),
                        }
                    }
                }
            }
            Payload::ImportSection(r) => {
                for group in r {
                    let group = group.map_err(|e| format!("import section: {e}"))?;
                    // Three import-group encodings in wasmparser 0.247.
                    // Only `Single` appears in stock LLVM output; others
                    // come from the compact-imports proposal and are
                    // handled here for completeness.
                    let tick = |ty: TypeRef,
                                imported_funcs: &mut u32,
                                imported_globals: &mut u32| match ty {
                        TypeRef::Func(_) | TypeRef::FuncExact(_) => *imported_funcs += 1,
                        TypeRef::Global(_) => *imported_globals += 1,
                        _ => {}
                    };
                    match group {
                        Imports::Single(_, imp) => {
                            tick(imp.ty, &mut imported_funcs, &mut imported_globals);
                        }
                        Imports::Compact1 { items, .. } => {
                            for item in items {
                                let item =
                                    item.map_err(|e| format!("import section: {e}"))?;
                                tick(item.ty, &mut imported_funcs, &mut imported_globals);
                            }
                        }
                        Imports::Compact2 { ty, names, .. } => {
                            for name in names {
                                let _ = name.map_err(|e| format!("import section: {e}"))?;
                                tick(ty, &mut imported_funcs, &mut imported_globals);
                            }
                        }
                    }
                }
            }
            Payload::FunctionSection(r) => {
                for ti in r {
                    func_type_for_local_idx
                        .push(ti.map_err(|e| format!("function section: {e}"))?);
                }
            }
            Payload::GlobalSection(r) => {
                for g in r {
                    let g = g.map_err(|e| format!("global section: {e}"))?;
                    global_types.push(g.ty);
                    let mut ops = g.init_expr.get_operators_reader();
                    let val = match ops.read() {
                        Ok(Operator::I32Const { value }) => Some(value as i64),
                        Ok(Operator::I64Const { value }) => Some(value),
                        _ => None,
                    };
                    global_init_i64.push(val);
                }
            }
            Payload::ExportSection(r) => {
                for exp in r {
                    let exp = exp.map_err(|e| format!("export section: {e}"))?;
                    exports.push((exp.name.to_string(), exp.kind, exp.index));
                }
            }
            _ => {}
        }
    }

    // Sort exports by name for deterministic output. BTreeMap doesn't
    // help here because we construct a Vec<Value> at the top level.
    exports.sort_by(|a, b| a.0.cmp(&b.0));

    let mut list = Vec::new();
    for (name, kind, index) in exports {
        if !shared::abi::export_is_tracked(&name) {
            continue;
        }
        let mut m: JsonMap = BTreeMap::new();
        m.insert("name".into(), json!(name));

        match kind {
            ExternalKind::Func | ExternalKind::FuncExact => {
                m.insert("kind".into(), json!("func"));
                let sig = if index < imported_funcs {
                    "<imported>".to_string()
                } else {
                    let local = (index - imported_funcs) as usize;
                    func_type_for_local_idx
                        .get(local)
                        .and_then(|ti| func_types.get(*ti as usize))
                        .map(format_func_type)
                        .unwrap_or_else(|| "<unknown>".into())
                };
                m.insert("signature".into(), json!(sig));
            }
            ExternalKind::Global => {
                m.insert("kind".into(), json!("global"));
                if index < imported_globals {
                    m.insert("type".into(), json!("<imported>"));
                } else {
                    let local = (index - imported_globals) as usize;
                    if let Some(gt) = global_types.get(local) {
                        m.insert("type".into(), json!(val_type_name(&gt.content_type)));
                        m.insert("mutable".into(), json!(gt.mutable));
                        if shared::abi::export_value_is_tracked(&name) && !gt.mutable {
                            if let Some(Some(v)) = global_init_i64.get(local) {
                                m.insert("value".into(), json!(v));
                            }
                        }
                    } else {
                        m.insert("type".into(), json!("<unknown>"));
                    }
                }
            }
            ExternalKind::Memory => {
                m.insert("kind".into(), json!("memory"));
            }
            ExternalKind::Table => {
                m.insert("kind".into(), json!("table"));
            }
            ExternalKind::Tag => {
                m.insert("kind".into(), json!("tag"));
            }
        }
        list.push(Value::Object(m.into_iter().collect()));
    }
    Ok(Value::Array(list))
}

fn format_func_type(f: &wasmparser::FuncType) -> String {
    let params: Vec<String> = f.params().iter().map(val_type_name).collect();
    let results: Vec<String> = f.results().iter().map(val_type_name).collect();
    format!("({}) -> ({})", params.join(","), results.join(","))
}

fn val_type_name(vt: &wasmparser::ValType) -> String {
    match vt {
        wasmparser::ValType::I32 => "i32",
        wasmparser::ValType::I64 => "i64",
        wasmparser::ValType::F32 => "f32",
        wasmparser::ValType::F64 => "f64",
        wasmparser::ValType::V128 => "v128",
        wasmparser::ValType::Ref(_) => "ref",
    }
    .to_string()
}

fn render_deterministic(root: &JsonMap) -> String {
    // Value::Object built from a BTreeMap serializes with BTreeMap's
    // alphabetical iteration, giving deterministic output.
    let value = Value::Object(root.clone().into_iter().collect());
    let mut s = serde_json::to_string_pretty(&value).expect("serialize");
    s.push('\n');
    s
}
