/* version.c */
/* Autogenerated by Makefile - DO NOT EDIT */

#include "version.h"
const char *version_string = "1.24.5";
const char *compilation_string = "wasm32posix-cc -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/usr/etc/wgetrc\" -DLOCALEDIR=\"/usr/share/locale\" -I. -I../lib -I../lib -I/Users/brandon/ai-src/wasm-posix-kernel/sysroot/include -DHAVE_LIBSSL -I/Users/brandon/ai-src/wasm-posix-kernel/sysroot/include -DNDEBUG -I/Users/brandon/ai-src/wasm-posix-kernel/examples/libs/openssl/openssl-install/include -I/Users/brandon/ai-src/wasm-posix-kernel/examples/libs/zlib/zlib-install/include";
const char *link_string = "wasm32posix-cc -I/Users/brandon/ai-src/wasm-posix-kernel/sysroot/include -DHAVE_LIBSSL -I/Users/brandon/ai-src/wasm-posix-kernel/sysroot/include -DNDEBUG -I/Users/brandon/ai-src/wasm-posix-kernel/examples/libs/openssl/openssl-install/include -I/Users/brandon/ai-src/wasm-posix-kernel/examples/libs/zlib/zlib-install/include -L/Users/brandon/ai-src/wasm-posix-kernel/examples/libs/openssl/openssl-install/lib -L/Users/brandon/ai-src/wasm-posix-kernel/examples/libs/zlib/zlib-install/lib -L/Users/brandon/ai-src/wasm-posix-kernel/sysroot/lib -lssl -lcrypto -L/Users/brandon/ai-src/wasm-posix-kernel/sysroot/lib -lz ../lib/libgnu.a ";
